### ISSUE TITLE
Support Yarn v2

### ISSUE THREAD

**Issue by ktsn** [ktsn/vue-auto-routing#72]
https://dev.to/arcanis/introducing-yarn-2-4eh1#readonly-packages

Since Yarn v2 makes packages read-only, it is not allowed that vue-auto-routing generates routing file inside this lib.

The workaround is simple, to allow users specifying output path and import it.

With this workaround, users need to rewrite the import statement for `vue-auto-routing` to the new output path:

```js
// before
import routes from 'vue-auto-routing'

// after (example)
import routes from '@/__routes__'
```

**Comment by thefoxie** [comment]
@ktsn any update on this?

**Comment by bencelang** [comment]
This behavior also creates a race condition in a monorepo during a concurrent build when two or more packages use `vue-auto-routing`. A fix for this would also require minor changes in `vue-cli-plugin-auto-routing`.

Also, imo a solution should be able to pass custom prettier configuration to `vue-route-generator` or the cli plugin should add the default output file to the `.gitignore`, otherwise the generated output might brake builds with custom prettier rules enabled. 

I'm happy to help by implementing this! :smile:
